baseURL = "http://deathworlders.online/"
languageCode = "en-gb"
title = "The Deathworlders Online"

theme = "kiera"

pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Philip R. Johnson"       #Author name
    github = "HamboneHFY"     #Github username
    gitlab = ""     #Gitlab username
    linkedin = ""   #LinkedIn username
    facebook = ""   #Facebook username
    twitter = ""    #Twitter username
    instagram = ""  #Instagram username

[params]
    tagline = ""
